[package]
name = "fluidsim"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.13.0"
egui = "0.30.0"
futures = "0.3.31"
ggez = { git = "https://github.com/ggez/ggez", branch = "devel" }
itertools = "0.13.0"
lazy_static = "1.5.0"
log = "0.4.22"
thiserror = { git = "https://github.com/onlycs/thiserror" }

[dependencies.skuld]
git = "https://github.com/onlycs/asgard"
default-features = false
features = ["facade"]
