[package]
name = "fluidsim"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.13.0"
ggez = { git = "https://github.com/ggez/ggez", branch = "devel" }
log = "0.4.22"
skuld = { git = "https://github.com/onlycs/asgard", version = "0.1.0", default-features = false, features = [
	"facade",
] }
thiserror = { git = "https://github.com/onlycs/thiserror", version = "1.0.63" }
