[package]
name = "fluidsim"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.13.0", features = ["unstable"] }
bevy = { version = "0.15.1", features = ["dynamic_linking", "wayland"] }
bevy_egui = "0.32.0"
bytemuck = "1.21.0"
egui = "0.30.0"
futures = "0.3.31"
ggez = { git = "https://github.com/ggez/ggez", branch = "devel" }
glam = "0.29.2"
itertools = "0.14.0"
lazy_static = "1.5.0"
log = { version = "0.4.22", features = ["max_level_debug"] }
rand = "0.8.5"
rayon = "1.10.0"
thiserror = { git = "https://github.com/onlycs/thiserror" }

[target.'cfg(target_os = "linux")'.dependencies]
hyprland = "0.4.0-beta.1"

[profile.dev]
opt-level = 1

[profile.dev.package.'*']
opt-level = 3

[profile.release]
lto = "thin"

[profile.wasm-release]
inherits = "release"
lto = "thin"
opt-level = "s"
strip = "debuginfo"
