[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
fluidsim = { path = "crates/fluidsim" }
gpu-shared = { path = "crates/gpu-shared" }

[profile.dev.build-override]
opt-level = 3
