[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }
CXXFLAGS = "-O2"

[build]
rustc-wrapper = "sccache"
rustflags = ["-Z", "threads=16"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"
